server:
  port: 9009
spring:
  rabbitmq:
    host: 192.168.0.109
  application:
    name: tensquare-sms
aliyun:
  sms:
    accessKeyId: LTAI4FpASe6nW9yXN2fgpp5a
    accessKeySecret: PtYaR1h0rGmNUUNlCxz08hy4nbA5VY
    template_code: SMS_183240329
    sign_name: 林间有风